<% secrets = Kamal::Secrets.new(destination: ENV["KAMAL_DESTINATION"]) %>

service: bank-frontend
image: <%= ENV.fetch("KAMAL_IMAGE") %>

servers:
  web:
    - <%= secrets["KAMAL_SERVER_IP"] %>

proxy:
  host: <%= ENV.fetch("KAMAL_HOST") %>
  app_port: 80
  ssl: true

registry:
  server: <%= ENV.fetch("KAMAL_REGISTRY_SERVER") %>
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  args:
    VITE_API_BASE_URL: <%= ENV.fetch("VITE_API_BASE_URL") %>

ssh:
  user: <%= ENV.fetch("KAMAL_SSH_USER", "root") %>
  key_data:
    - KAMAL_SSH_PRIVATE_KEY
